import Head from "next/head";
import axios from "axios";
import Original from "./../../components/Original/Original";
import Action from "./../../components/Action/Action";
import Romance from "./../../components/Romance/Romance";
import Comedy from "./../../components/Comedy/Comedy";
import Horror from "./../../components/Horror/Horror";
import Documentary from "./../../components/Documentary/Documentary";
import CoverSection from "./../../components/CoverSection/CoverSection";

export default function Home({
  originalData,
  actionData,
  romanceData,
  comedyData,
  horrorData,
  documentaryData,
}) {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CoverSection />
   
      <Action data={actionData} />
      <Romance data={romanceData} />
      <Comedy data={comedyData} />
      <Horror data={horrorData} />
      <Documentary data={documentaryData} />
      <Original data={originalData} />
    </div>
  );
}

export async function getStaticProps() {
  const originalResult = await axios.get(
    "https://api.themoviedb.org/3/discover/tv?api_key=aad7795cbcd9e9b03e57f734a26af4bb&with_networks=213"
  );

  const actionResult = await axios.get(
    "https://api.themoviedb.org/3/discover/movie?api_key=aad7795cbcd9e9b03e57f734a26af4bb&with_genres=28"
  );

  const romanceResult = await axios.get(
    "https://api.themoviedb.org/3/discover/movie?api_key=aad7795cbcd9e9b03e57f734a26af4bb&with_genres=10749"
  );
  const comedyResult = await axios.get(
    "https://api.themoviedb.org/3/discover/movie?api_key=aad7795cbcd9e9b03e57f734a26af4bb&with_genres=35"
  );
  const horrorResult = await axios.get(
    "https://api.themoviedb.org/3/discover/movie?api_key=aad7795cbcd9e9b03e57f734a26af4bb&with_genres=27"
  );
  const documentaryResult = await axios.get(
    "https://api.themoviedb.org/3/discover/movie?api_key=aad7795cbcd9e9b03e57f734a26af4bb&with_genres=99"
  );

  return {
    props: {
      originalData: originalResult.data.results,
      actionData: actionResult.data.results,
      romanceData: romanceResult.data.results,
      comedyData: comedyResult.data.results,
      horrorData: horrorResult.data.results,
      documentaryData: documentaryResult.data.results,
    },
    revalidate: 1,
  };
}
